import json
import logging
import os
import subprocess
from typing import Dict, Any, List
from celery import shared_task
from ..models.hackathon import HackathonDocument
from ..firebase.client import upsert_hackathon, get_firestore_client

logger = logging.getLogger(__name__)


@shared_task(name="src.scheduler.tasks.run_ingestion_pipeline_task")
def run_ingestion_pipeline_task(dry_run: bool = False) -> Dict[str, Any]:
    """
    Celery background task that executes the complete Phase 2 & 3 pipeline:
    1. Runs the live Scrapy spiders (via subprocess to avoid Celery/Twisted reactor conflicts).
    2. Upserts clean deduplicated records into Firestore /hackathons collection.
    """
    logger.info("Starting automated live ingestion pipeline task (dry_run=%s)...", dry_run)

    script_path = os.path.abspath(os.path.join(os.path.dirname(__file__), "..", "..", "scripts", "run_local_scrape.py"))
    
    # Run the scraping script in a separate process
    try:
        subprocess.run(["python", script_path], check=True, capture_output=True, text=True)
    except subprocess.CalledProcessError as e:
        logger.error("Scraping subprocess failed: %s", e.stderr)
        return {"status": "ERROR", "message": "Scraping subprocess failed."}

    # Read the output JSON generated by the scraping script
    out_path = os.path.abspath(os.path.join(os.path.dirname(__file__), "..", "..", "output", "hackathons_dump.json"))
    
    if not os.path.exists(out_path):
        logger.error("Output file %s not found. Scraping might have yielded no results.", out_path)
        return {"status": "ERROR", "message": "No scrape output file found."}
        
    with open(out_path, "r", encoding="utf-8") as f:
        raw_items = json.load(f)
        
    unique_records = [HackathonDocument.model_validate(item) for item in raw_items]
    logger.info("Unique records loaded from scrape output: %d", len(unique_records))

    upserted_ids: List[str] = []
    failed_ids: List[str] = []

    if not dry_run:
        try:
            db_client = get_firestore_client()
            for doc in unique_records:
                try:
                    doc_id = upsert_hackathon(doc, db=db_client)
                    upserted_ids.append(doc_id)
                except Exception as e:
                    logger.error("Failed to upsert hackathon %s: %s", doc.id, str(e))
                    failed_ids.append(doc.id)
        except Exception as e:
            logger.warning(
                "Firestore client not connected or ADC unavailable (%s). Performing simulated in-memory upsert.",
                str(e),
            )
            upserted_ids = [doc.id for doc in unique_records]
    else:
        upserted_ids = [doc.id for doc in unique_records]

    result = {
        "status": "SUCCESS",
        "unique_records": len(unique_records),
        "upserted_count": len(upserted_ids),
        "failed_count": len(failed_ids),
    }
    logger.info("Ingestion pipeline task finished: %s", result)
    return result


@shared_task(name="src.scheduler.tasks.update_user_recommendations_task")
def update_user_recommendations_task(user_id: str, user_profile: Dict[str, Any], dry_run: bool = False) -> Dict[str, Any]:
    """
    Celery background task that calculates personalized recommendations for a user
    and writes the RankedHackathon IDs directly to /users/{user_id}/recommendations/latest.
    """
    logger.info("Starting recommendation update task for user %s (dry_run=%s)", user_id, dry_run)
    from ..recommendation.service import generate_recommendations_for_user

    # For recommendation engine, we can just read the existing JSON dump if it exists,
    # rather than triggering a full re-scrape for every single user calculation.
    out_path = os.path.abspath(os.path.join(os.path.dirname(__file__), "..", "..", "output", "hackathons_dump.json"))
    
    if not os.path.exists(out_path):
        # Fallback to a live scrape if no data exists at all
        run_ingestion_pipeline_task(dry_run=True)
        
    with open(out_path, "r", encoding="utf-8") as f:
        raw_items = json.load(f)
        hackathons = [HackathonDocument.model_validate(item) for item in raw_items]

    rec_doc = generate_recommendations_for_user(
        user_id=user_id,
        user_profile=user_profile,
        hackathons=hackathons,
        top_n=10,
        dry_run=dry_run,
    )

    res = {
        "status": "SUCCESS",
        "user_id": user_id,
        "ranked_count": len(rec_doc.rankedHackathons),
        "top_hackathon_id": rec_doc.rankedHackathons[0].hackathonId if rec_doc.rankedHackathons else None,
    }
    logger.info("Recommendation task finished for user %s: %s", user_id, res)
    return res
